import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeContextProvider } from "@/context/ThemeContext";
import ThemeToggleButton from "@/components/button/ThemeToggleButton";
import ReactQueryContext from "@/context/ReactQueryContext";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Dashboard Tax Center",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body>
        <AppRouterCacheProvider>
          <ReactQueryContext>
            <ThemeContextProvider>
              {children}
              <ThemeToggleButton />
            </ThemeContextProvider>
          </ReactQueryContext>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
